class _BotCommands:
    def __init__(self):
        self.StartCommand = 'starthr'
        self.MirrorCommand = 'mirrorhr'
        self.UnzipMirrorCommand = 'unzipmirrorhr'
        self.TarMirrorCommand = 'tarmirrorhr'
        self.CancelMirror = 'cancelhr'
        self.CancelAllCommand = 'cancelallhr'
        self.ListCommand = 'listhr'
        self.StatusCommand = 'statushr'
        self.AuthorizedUsersCommand = 'usershr'
        self.AuthorizeCommand = 'authorizehr'
        self.UnAuthorizeCommand = 'unauthorizehr'
        self.AddSudoCommand = 'addsudohr'
        self.RmSudoCommand = 'rmsudohr'
        self.PingCommand = 'pinghr'
        self.RestartCommand = 'restarthr'
        self.StatsCommand = 'statshr'
        self.HelpCommand = 'helphr'
        self.LogCommand = 'loghr'
        self.SpeedCommand = 'speedtesthr'
        self.CloneCommand = 'clonehr'
        self.CountCommand = 'counthr'
        self.WatchCommand = 'watchhr'
        self.TarWatchCommand = 'tarwatchhr'
        self.DeleteCommand = 'delhr'
        self.UsageCommand = 'usagehr'

BotCommands = _BotCommands()
